### ISSUE TITLE
Indentation level of some codes

### ISSUE THREAD

**Issue by Qinyu-Allen-Zhao** [j-min/DSG#1]
https://github.com/j-min/DSG/blob/3f844c1dadd141e5c7b3e9d68f3889208c9b6248/query_utils.py#L350-L389

Hello,

Thank you for sharing your great work!

Upon attempting to generate a DSG, I've noticed that the indentation of certain lines may be incorrect. It appears they should be indented one level less, as the current formatting causes an exception to be thrown. Once I adjusted the indentation level, the generation process proceeded without any issues.

Qinyu

**Comment by j-min** [comment]
You're right, thanks for the catch! I just fixed the indentation the repo.
