### ISSUE TITLE
Releasing the human likert scale for TIFA160?

### ISSUE THREAD

**Issue by linzhiqiu** [j-min/DSG#3]
The paper mentions that you collect the human likert scale (1-5) for TIFA160 on 5 diffusion models. Will the likert scale + generated images be released?

**Comment by j-min** [comment]
Thanks for your interest in our project. We have just released the human Likert scores on TIFA160 prompts in our GitHub repo - https://github.com/j-min/DSG/blob/main/tifa160-likert-anns.csv
Hope this helps.
