### ISSUE TITLE
detailed dependancy for reproducing CLIPScore TIFA160

### ISSUE THREAD

**Issue by long8v** [j-min/DSG#6]
Hey there, thank you for great work! It really inspires my work.
I tried to reproduce Table 12, specifically CLIPScore.
<img width="672" alt="image" src="https://github.com/user-attachments/assets/45ed66eb-ec7a-49e5-bf06-bf09e811d0cc">

I found in CLIPScore repo, some packages (such as Pillow 8.4 vs 9.4 / torch 1.7 vs 2.0 / numpy 1.20.0 or higher) returns different value, subsequently return different correlation value. Also, clipscore employs [prefix](https://github.com/jmhessel/clipscore/blob/main/clipscore.py#L67) `A photo depicts `. However, I found [TIFAv1](https://github.com/Yushi-Hu/tifa/blob/main/human_annotations/human_annotations.json) CLIPScore corresponds with without any prefix. 
When I reproduce with TIFA160 and it returns slightly different values
(DSG report) 0.276 / 0.191
- Pilllow==9.4.0
  - prefix "A photo depicts ":  0.299 / 0.226
  - prefix "": 0.279/ 0.209
- Pillow==8.4.0
  - prefix "A photo depicts ":  0.285 / 0.215
  - prefix "": 0.266 / 0.199

It would be really helpful if you provide package dependancy you used for the paper and whether you used prefix when calculating CLIPScore.
Thanks!

**Comment by j-min** [comment]
@wangsu-google-language - could you please check the package versions?

**Comment by long8v** [comment]
I found a mistake in my code.
When I fix this, I successfully reproduce Table 12 but without template ["A photo depicts "](https://github.com/jmhessel/clipscore/blob/main/clipscore.py#L67). 

(DSG report) 
- 0.276 / 0.191

(my result in PIL 8.4.0)
- template "A photo depicts ": (spearman) 0.2990781700406022 (kendall) 0.2070432781113664
- template "": (spearman) 0.2779111660592737 (kendall) 0.19136838513786647

Thanks!
